name = "SpectralDistances"
uuid = "2b0dec9d-f767-4f95-9e73-7df56487de68"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "0.1.0"

[deps]
BackwardsLinalg = "442b4e1a-8b9d-11e9-03b0-f14b31742153"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
TotalLeastSquares = "028f657a-7ace-5159-a694-8cfd97933b0c"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
ThreadTools = "0.1"
TotalLeastSquares = "1.0"
julia = "1.3"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "ForwardDiff", "Zygote"]
